# Generated by Django 6.0.6 on 2026-07-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Queries'},
        ),
    ]
